/**
 * lib/participants/qr.ts
 *
 * Generates the participant's QR pass. The QR encodes ONLY the random
 * `qr_token` (16 secure random bytes, generated by the DB — see the
 * participants table default) via a verification URL — never the internal
 * uuid `id` and never the human-readable `participant_code` alone, which
 * would be guessable/enumerable. Scanning it is meaningless without the
 * server-side lookup in checkin.ts.
 */
import QRCode from "qrcode";

export interface QrOptions {
  /** Base URL of your deployed app, e.g. https://musabaqa.example.com */
  appBaseUrl: string;
}

export function buildCheckinUrl(qrToken: string, opts: QrOptions): string {
  return `${opts.appBaseUrl.replace(/\/$/, "")}/checkin/${qrToken}`;
}

export function buildVerificationUrl(qrToken: string, opts: QrOptions): string {
  return `${opts.appBaseUrl.replace(/\/$/, "")}/verify/${qrToken}`;
}

async function toDataUrl(url: string): Promise<string> {
  return QRCode.toDataURL(url, {
    errorCorrectionLevel: "M",
    margin: 2,
    width: 320,
  });
}

/** Returns a PNG data URL (e.g. for <img src=...> or embedding in a certificate/PDF). */
export async function generateParticipantQrDataUrl(qrToken: string, opts: QrOptions): Promise<string> {
  return toDataUrl(buildCheckinUrl(qrToken, opts));
}

/** Same as generateParticipantQrDataUrl but points at the public certificate verification page. */
export async function generateVerificationQrDataUrl(qrToken: string, opts: QrOptions): Promise<string> {
  return toDataUrl(buildVerificationUrl(qrToken, opts));
}

/** Returns raw SVG markup, useful for print-quality certificates/badges. */
export async function generateParticipantQrSvg(qrToken: string, opts: QrOptions): Promise<string> {
  const url = buildCheckinUrl(qrToken, opts);
  return QRCode.toString(url, { type: "svg", errorCorrectionLevel: "M", margin: 2 });
}
