/**
 * lib/participants/register.ts
 *
 * Spec section 12: public participant registration. All eligibility checks
 * (registration window, category capacity, age, gender restriction) happen
 * here, server-side — never trust a frontend form to have already validated
 * these. The participant_code is generated by a DB trigger (see migration
 * musabaqa_participant_code_generation), so callers never set it themselves.
 */
import type { SupabaseClient } from "@supabase/supabase-js";
import { writeAuditLog } from "../audit/log";

export interface RegisterParticipantInput {
  fullName: string;
  dateOfBirth?: string; // ISO date, e.g. "2010-04-12"
  gender?: "Male" | "Female";
  country?: string;
  state?: string;
  lga?: string;
  city?: string;
  organization?: string;
  teacher?: string;
  phone?: string;
  email?: string;
  photoUrl?: string;
  emergencyContactName?: string;
  emergencyContactPhone?: string;
  competitionId: string;
  categoryId: string;
  /** Set once the participant has a Supabase Auth account (self-service login). */
  userId?: string;
}

export class RegistrationError extends Error {}

function ageInYears(dateOfBirth: string, asOf: Date): number {
  const dob = new Date(dateOfBirth);
  let age = asOf.getFullYear() - dob.getFullYear();
  const monthDiff = asOf.getMonth() - dob.getMonth();
  if (monthDiff < 0 || (monthDiff === 0 && asOf.getDate() < dob.getDate())) age--;
  return age;
}

export interface RegisteredParticipant {
  id: string;
  participant_code: string;
  qr_token: string;
  full_name: string;
  status: string;
}

export async function registerParticipant(
  db: SupabaseClient,
  input: RegisterParticipantInput
): Promise<RegisteredParticipant> {
  if (!input.fullName?.trim()) {
    throw new RegistrationError("Full name is required.");
  }

  // --- Load competition + category and validate eligibility server-side ---
  const { data: competition, error: compError } = await db
    .schema("musabaqa")
    .from("competitions")
    .select("id, status, registration_start, registration_end, max_participants")
    .eq("id", input.competitionId)
    .maybeSingle();
  if (compError) throw compError;
  if (!competition) throw new RegistrationError("Competition not found.");

  if (competition.status !== "REGISTRATION_OPEN") {
    throw new RegistrationError("Registration is not currently open for this competition.");
  }

  const today = new Date();
  if (competition.registration_start && today < new Date(competition.registration_start)) {
    throw new RegistrationError("Registration has not started yet.");
  }
  if (competition.registration_end && today > new Date(competition.registration_end)) {
    throw new RegistrationError("Registration has closed.");
  }

  const { data: category, error: catError } = await db
    .schema("musabaqa")
    .from("competition_categories")
    .select("id, status, age_min, age_max, gender_restriction, competition_id")
    .eq("id", input.categoryId)
    .maybeSingle();
  if (catError) throw catError;
  if (!category || category.competition_id !== input.competitionId) {
    throw new RegistrationError("Category not found for this competition.");
  }
  if (category.status !== "ACTIVE") {
    throw new RegistrationError("This category is not open for registration.");
  }

  if (category.age_min != null || category.age_max != null) {
    if (!input.dateOfBirth) {
      throw new RegistrationError("Date of birth is required for this category's age restriction.");
    }
    const age = ageInYears(input.dateOfBirth, today);
    if (category.age_min != null && age < category.age_min) {
      throw new RegistrationError(`Minimum age for this category is ${category.age_min}.`);
    }
    if (category.age_max != null && age > category.age_max) {
      throw new RegistrationError(`Maximum age for this category is ${category.age_max}.`);
    }
  }

  if (category.gender_restriction !== "ANY") {
    if (!input.gender) {
      throw new RegistrationError("Gender is required for this category.");
    }
    const wanted = category.gender_restriction === "MALE" ? "Male" : "Female";
    if (input.gender !== wanted) {
      throw new RegistrationError(`This category is restricted to ${wanted} participants.`);
    }
  }

  if (competition.max_participants != null) {
    const { count, error: countError } = await db
      .schema("musabaqa")
      .from("participant_competitions")
      .select("*", { count: "exact", head: true })
      .eq("competition_id", input.competitionId);
    if (countError) throw countError;
    if ((count ?? 0) >= competition.max_participants) {
      throw new RegistrationError("This competition has reached its maximum number of participants.");
    }
  }

  // --- Insert participant (participant_code + qr_token auto-generated by DB) ---
  const { data: participant, error: insertError } = await db
    .schema("musabaqa")
    .from("participants")
    .insert({
      user_id: input.userId ?? null,
      full_name: input.fullName.trim(),
      date_of_birth: input.dateOfBirth ?? null,
      gender: input.gender ?? null,
      country: input.country ?? null,
      state: input.state ?? null,
      lga: input.lga ?? null,
      city: input.city ?? null,
      organization: input.organization ?? null,
      teacher: input.teacher ?? null,
      phone: input.phone ?? null,
      email: input.email ?? null,
      photo_url: input.photoUrl ?? null,
      emergency_contact_name: input.emergencyContactName ?? null,
      emergency_contact_phone: input.emergencyContactPhone ?? null,
      status: "PENDING",
    })
    .select("id, participant_code, qr_token, full_name, status")
    .single();

  if (insertError || !participant) {
    throw insertError ?? new RegistrationError("Failed to create participant record.");
  }

  // --- Link to the competition/category ---
  const { error: linkError } = await db.schema("musabaqa").from("participant_competitions").insert({
    participant_id: participant.id,
    competition_id: input.competitionId,
    category_id: input.categoryId,
    status: "REGISTERED",
  });

  if (linkError) {
    // Best-effort rollback of the orphaned participant row so a failed
    // registration doesn't leave a dangling record with no competition link.
    await db.schema("musabaqa").from("participants").delete().eq("id", participant.id);
    throw linkError;
  }

  await writeAuditLog(db, {
    userId: input.userId ?? null,
    action: "participant_registration",
    entityType: "participant",
    entityId: participant.id,
    newValue: { participant_code: participant.participant_code, competitionId: input.competitionId, categoryId: input.categoryId },
  });

  return participant as RegisteredParticipant;
}
